[package]
name = "gambatee"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
serenity = { version = "0.12.4", features = ["cache", "client", "gateway", "model"] }
tokio = { version = "1.47.1", features = ["full"] }
