apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres-main
    type: postgres
    access: proxy
    url: postgres:5432
    user: $POSTGRES_USER
    isDefault: true
    editable: false
    jsonData:
      database: $POSTGRES_DB
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: $POSTGRES_PASSWORD
